name: CI

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test

    env:
      DATABASE_URL: postgres://postgres:password@localhost/dev

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start containers
      run: docker-compose up -d

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test -- --test-threads=1

    # - name: Stop containers
    #   run: docker-compose down
